package com.example.marketflow.messaging;

public enum MarketFlowEventType {
    ORDER_CREATED,
    ORDER_PAID,
    ORDER_CANCELLED,
    ORDER_COMPLETED,
    ORDER_REFUNDED,
    SELLER_STARTED_WORK,
    SELLER_SENT_PRODUCT,
    USER_RECEIVED_PRODUCT,
    SELLER_MONEY_PENDING,
    PLATFORM_COMMISSION_ADDED,
    SELLER_MONEY_AVAILABLE,
    SELLER_WITHDRAWAL_COMPLETED,
    SELLER_MONEY_RETURNED,
    PLATFORM_COMMISSION_RETURNED
}
